[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "aws.sns"
version = "4.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Communication/Notifications", "Cost/Freemium", "Vendor/Amazon"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.sns"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
