name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ stdlib-release-pipeline ]

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/release-package-connector-template.yml@main
    secrets: inherit
    with:
      package-name: aws.sns
      package-org: ballerinax
      additional-build-flags: "-x :aws.sns-examples:build"
      additional-test-flags: "-x :aws.sns-examples:test"
